#pragma once

#define MTRL_std2d L"Std2DMtrl"
#define MTRL_std3d L"Std3DMtrl"
#define MTRL_deferred L"Std3D_DeferredMtrl"
#define MTRL_dirlight L"DirLightMtrl"
#define MTRL_pointlight L"PointLightMtrl"
#define MTRL_spotlight L"SpotLightMtrl"
#define MTRL_merge L"MergeMtrl"
#define MTRL_decal L"DecalMtrl"
#define MTRL_background L"BackgroundMtrl"
#define MTRL_tilemap L"TileMapMtrl"
#define MTRL_particle L"ParticleMtrl"
#define MTRL_skybox L"SkyBoxMtrl"
#define MTRL_grayfilter L"GrayFilterMtrl"
#define MTRL_distortion L"DistortionMtrl"
#define MTRL_debugshape L"DebugShapeMtrl"