#pragma once

#define FXdebug L"shader\\debug.fx"
#define FXdecal L"shader\\decal.fx"
#define FXfunc L"shader\\func.fx"
#define FXlandscape L"shader\\landscape.fx"
#define FXlight L"shader\\light.fx"
#define FXmerge L"shader\\merge.fx"
#define FXparticle L"shader\\particle.fx"
#define FXparticle_update L"shader\\particle_update.fx"
#define FXpostprocess L"shader\\postprocess.fx"
#define FXsetcolor L"shader\\setcolor.fx"
#define FXshadowmap L"shader\\shadowmap.fx"
#define FXskybox L"shader\\skybox.fx"
#define FXstd2d L"shader\\std2d.fx"
#define FXstd3d L"shader\\std3d.fx"
#define FXstd3d_deferred L"shader\\std3d_deferred.fx"
#define FXstruct L"shader\\struct.fx"
#define FXtess L"shader\\tess.fx"
#define FXtilemap L"shader\\tilemap.fx"
#define FXvalue L"shader\\value.fx"
