#pragma once

#define FBXHouse L"fbx\\House.fbx"
#define FBXHouse_A L"fbx\\House_A.fbx"
#define FBXHouse_B L"fbx\\House_B.fbx"
#define FBXHouse_C L"fbx\\House_C.fbx"
#define FBXHouse_D L"fbx\\House_D.fbx"
#define FBXHouse_E L"fbx\\House_E.fbx"
#define FBXMap_DirtEdge L"fbx\\Map_DirtEdge.fbx"
#define FBXMap_Grass L"fbx\\Map_Grass.fbx"
#define FBXMap_Hills L"fbx\\Map_Hills.fbx"
#define FBXMap_Parcel L"fbx\\Map_Parcel.fbx"
#define FBXMap_Road L"fbx\\Map_Road.fbx"
#define FBXMap_Sidewalk L"fbx\\Map_Sidewalk.fbx"
#define FBXMonster L"fbx\\Monster.fbx"
#define FBXrock1 L"fbx\\rock1.fbx"
#define FBXserika_better2 L"fbx\\serika_better2.fbx"
#define FBXserika_better3 L"fbx\\serika_better3.fbx"
#define FBXTent L"fbx\\Tent.fbx"
#define FBXTower_A L"fbx\\Tower_A.fbx"
#define FBXTower_B L"fbx\\Tower_B.fbx"
#define FBXTower_C L"fbx\\Tower_C.fbx"
#define FBXTower_D L"fbx\\Tower_D.fbx"
