#pragma once

#define GRPSHADERDebugShapeShader L"GraphicsShader\\DebugShapeShader.gs"
#define GRPSHADERDebugShapeShader_Inst_0 L"GraphicsShader\\DebugShapeShader_Inst_0.gs"
#define GRPSHADERDecalShader L"GraphicsShader\\DecalShader.gs"
#define GRPSHADERDirLightShader L"GraphicsShader\\DirLightShader.gs"
#define GRPSHADERDistortionShader L"GraphicsShader\\DistortionShader.gs"
#define GRPSHADEREffectShader L"GraphicsShader\\EffectShader.gs"
#define GRPSHADERGrayFilterShader L"GraphicsShader\\GrayFilterShader.gs"
#define GRPSHADERMergeShader L"GraphicsShader\\MergeShader.gs"
#define GRPSHADERParticleRenderShader L"GraphicsShader\\ParticleRenderShader.gs"
#define GRPSHADERPointLightShader L"GraphicsShader\\PointLightShader.gs"
#define GRPSHADERShadowMapShader L"GraphicsShader\\ShadowMapShader.gs"
#define GRPSHADERSkyBoxShader L"GraphicsShader\\SkyBoxShader.gs"
#define GRPSHADERSpotLightShader L"GraphicsShader\\SpotLightShader.gs"
#define GRPSHADERStd2DShader L"GraphicsShader\\Std2DShader.gs"
#define GRPSHADERStd3DShader L"GraphicsShader\\Std3DShader.gs"
#define GRPSHADERStd3D_DeferredShader L"GraphicsShader\\Std3D_DeferredShader.gs"
#define GRPSHADERTileMapShader L"GraphicsShader\\TileMapShader.gs"
